DiamondShopSystem.RazorWebApp/Pages/CustomerPage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.CustomerPage
{
    public class CreateModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public CreateModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Customer.Add(Customer);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/CustomerPage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.CustomerPage
{
    public class DeleteModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public DeleteModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FirstOrDefaultAsync(m => m.CustomerId == id);

            if (customer == null)
            {
                return NotFound();
            }
            else
            {
                Customer = customer;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer != null)
            {
                Customer = customer;
                _context.Customer.Remove(Customer);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/CustomerPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.CustomerPage
{
    public class DetailsModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public DetailsModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        public Customer Customer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }
            else
            {
                Customer = customer;
            }
            return Page();
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/CustomerPage/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.CustomerPage
{
    public class EditModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public EditModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer =  await _context.Customer.FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }
            Customer = customer;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Customer).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CustomerExists(Customer.CustomerId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.CustomerId == id);
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/DiamondSettingPage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.DiamondSettingPage
{
    public class CreateModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public CreateModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public DiamondSetting DiamondSetting { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.DiamondSetting.Add(DiamondSetting);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/DiamondSettingPage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.DiamondSettingPage
{
    public class DeleteModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public DeleteModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        [BindProperty]
        public DiamondSetting DiamondSetting { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diamondsetting = await _context.DiamondSetting.FirstOrDefaultAsync(m => m.DiamondSettingId == id);

            if (diamondsetting == null)
            {
                return NotFound();
            }
            else
            {
                DiamondSetting = diamondsetting;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diamondsetting = await _context.DiamondSetting.FindAsync(id);
            if (diamondsetting != null)
            {
                DiamondSetting = diamondsetting;
                _context.DiamondSetting.Remove(DiamondSetting);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/DiamondSettingPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.DiamondSettingPage
{
    public class DetailsModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public DetailsModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        public DiamondSetting DiamondSetting { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diamondsetting = await _context.DiamondSetting.FirstOrDefaultAsync(m => m.DiamondSettingId == id);
            if (diamondsetting == null)
            {
                return NotFound();
            }
            else
            {
                DiamondSetting = diamondsetting;
            }
            return Page();
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/DiamondSettingPage/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DiamondShopSystem.DataAccess.Models;
using DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext;

namespace DiamondShopSystem.RazorWebApp.Pages.DiamondSettingPage
{
    public class EditModel : PageModel
    {
        private readonly DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs _context;

        public EditModel(DiamondShopSystem.DataAccess.Models.Net1710_221_6_DiamondShopSystemContext.cs context)
        {
            _context = context;
        }

        [BindProperty]
        public DiamondSetting DiamondSetting { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var diamondsetting =  await _context.DiamondSetting.FirstOrDefaultAsync(m => m.DiamondSettingId == id);
            if (diamondsetting == null)
            {
                return NotFound();
            }
            DiamondSetting = diamondsetting;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(DiamondSetting).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DiamondSettingExists(DiamondSetting.DiamondSettingId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DiamondSettingExists(int id)
        {
            return _context.DiamondSetting.Any(e => e.DiamondSettingId == id);
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/OrderPage/Index.cshtml.cs
using DiamondShopSystem.Business.Business.Interfaces;
using DiamondShopSystem.Business.Dtos;
using DiamondShopSystem.Common.Dtos;
using DiamondShopSystem.DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace DiamondShopSystem.RazorWebApp.Pages.OrderPage
{
    public class IndexModel : PageModel
    {
        private readonly IOrderBusiness _orderBusiness;

        public IndexModel(IOrderBusiness orderBusiness)
        {
            _orderBusiness = orderBusiness;
        }

        public int PageNumber { get; set; }
        public int TotalPage { get; set; }
        public IList<Order> Orders { get; set; } = new List<Order>();

        [BindProperty(SupportsGet = true)]
        public QueryOrderDto QueryOrderDto { get; set; } = new QueryOrderDto();

        public async Task OnGetAsync(PageRequest pageRequest)
        {
            var queryOrderDto = JsonConvert.DeserializeObject<QueryOrderDto>(pageRequest.queryString) ?? new QueryOrderDto();
            var dataResult = await _orderBusiness.GetQueriedOrder(pageRequest.pageNumber, pageRequest.pageSize, queryOrderDto);
            var result = dataResult.Data as PaginatedResult<Order>;

            TempData["PageNumber"] = PageNumber = pageRequest.pageNumber;
            TempData["PageSize"] = pageRequest.pageSize;
            TempData["TotalPage"] = TotalPage = result?.TotalPages ?? 1;
            TempData["QueryString"] = pageRequest.queryString;
            QueryOrderDto = queryOrderDto;

            Orders = result?.Results ?? new List<Order>();
        }

        public IActionResult OnPostFilter()
        {
            int pageNumber = (int)(TempData["PageNumber"] ?? 1);
            int pageSize = (int)(TempData["PageSize"] ?? 1);
            int totalPage = (int)(TempData["TotalPage"] ?? 1);
            string queryJson = JsonConvert.SerializeObject(QueryOrderDto);
            return RedirectToPage("Index", new PageRequest()
            {
                pageNumber = pageNumber,
                pageSize = pageSize,
                totalPage = totalPage,
                queryString = queryJson
            });
        }

        public IActionResult OnPostPrevPage()
        {
            int pageNumber = (int)(TempData["PageNumber"] ?? 1);
            if (pageNumber > 1)
            {
                pageNumber--;
            }
            int pageSize = (int)(TempData["PageSize"] ?? 1);
            int totalPage = (int)(TempData["TotalPage"] ?? 1);
            string queryJson = (string)(TempData["QueryString"] ?? string.Empty);
            return RedirectToPage("Index", new PageRequest()
            {
                pageNumber = pageNumber,
                pageSize = pageSize,
                totalPage = totalPage,
                queryString = queryJson
            });
        }

        public IActionResult OnPostNextPage()
        {
            int pageNumber = (int)(TempData["PageNumber"] ?? 1);
            int totalPage = (int)(TempData["TotalPage"] ?? 1);
            if (pageNumber < totalPage)
            {
                pageNumber++;
            }
            int pageSize = (int)(TempData["PageSize"] ?? 1);
            string queryJson = (string)(TempData["QueryString"] ?? string.Empty);
            return RedirectToPage("Index", new PageRequest()
            {
                pageNumber = pageNumber,
                pageSize = pageSize,
                totalPage = totalPage,
                queryString = queryJson
            });
        }
    }
}

DiamondShopSystem.RazorWebApp/Pages/ProductPage/Create.cshtml
@page
@model DiamondShopSystem.RazorWebApp.Pages.ProductPage.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product.ProductName" class="control-label"></label>
                <input asp-for="Product.ProductName" class="form-control" />
                <span asp-validation-for="Product.ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.DiamondSettingId" class="control-label"></label>
                <select asp-for="Product.DiamondSettingId" class ="form-control" asp-items="ViewBag.DiamondSettingId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Product.Description" class="control-label"></label>
                <input asp-for="Product.Description" class="form-control" />
                <span asp-validation-for="Product.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.CreateAt" class="control-label"></label>
                <input asp-for="Product.CreateAt" class="form-control" />
                <span asp-validation-for="Product.CreateAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.UpdateAt" class="control-label"></label>
                <input asp-for="Product.UpdateAt" class="form-control" />
                <span asp-validation-for="Product.UpdateAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Price" class="control-label"></label>
                <input asp-for="Product.Price" class="form-control" />
                <span asp-validation-for="Product.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Warranty" class="control-label"></label>
                <input asp-for="Product.Warranty" class="form-control" />
                <span asp-validation-for="Product.Warranty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Status" class="control-label"></label>
                <input asp-for="Product.Status" class="form-control" />
                <span asp-validation-for="Product.Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.StartDate" class="control-label"></label>
                <input asp-for="Product.StartDate" class="form-control" />
                <span asp-validation-for="Product.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.EndDate" class="control-label"></label>
                <input asp-for="Product.EndDate" class="form-control" />
                <span asp-validation-for="Product.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Terms" class="control-label"></label>
                <input asp-for="Product.Terms" class="form-control" />
                <span asp-validation-for="Product.Terms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.SideStoneId" class="control-label"></label>
                <select asp-for="Product.SideStoneId" class ="form-control" asp-items="ViewBag.SideStoneId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Product.SideStoneAmount" class="control-label"></label>
                <input asp-for="Product.SideStoneAmount" class="form-control" />
                <span asp-validation-for="Product.SideStoneAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.MainDiamondId" class="control-label"></label>
                <select asp-for="Product.MainDiamondId" class ="form-control" asp-items="ViewBag.MainDiamondId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DiamondShopSystem.RazorWebApp/Pages/ProductPage/Index.cshtml
@page
@model DiamondShopSystem.RazorWebApp.Pages.ProductPage.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<div class="container mt-5">
    <h2>Filter Products</h2>
    <form id="queryForm" class="d-flex flex-wrap gap-2" asp-page-handler="Filter">
        <div class="form-group ">
            <label asp-for="queryProductDto.ProductName" class="control-label">Name</label>
            <input asp-for="queryProductDto.ProductName" class="form-control" />
        </div>
        <div class="form-group ">
            <label asp-for="queryProductDto.UpperPrice" class="control-label">Upper Price</label>
            <input asp-for="queryProductDto.UpperPrice" class="form-control" />
        </div>
        <div class="form-group ">
            <label asp-for="queryProductDto.LowerPrice" class="control-label">Lower Price</label>
            <input asp-for="queryProductDto.LowerPrice" class="form-control" />
        </div>
        <div class="form-group ">
            <label asp-for="queryProductDto.Description" class="control-label">Description</label>
            <input asp-for="queryProductDto.Description" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="queryProductDto.Status" class="control-label">Status</label>
            <input asp-for="queryProductDto.Status" class="form-control" />
        </div>
        <div class="form-group col-12">
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].Warranty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].Terms)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].SideStoneAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].DiamondSetting)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].MainDiamond)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product[0].SideStone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Product) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Warranty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Terms)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SideStoneAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiamondSetting.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MainDiamond.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SideStone.Name)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.ProductId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div class="container mt-5">
    <div class="d-flex flex-wrap justify-content-center gap-2">
        <div class="form-group">
            <form method="post" asp-page-handler="PrevPage">
                <button type="submit" class="btn btn-primary">Previous Page</button>
            </form>
        </div>
        <div class="form-group ">
            @* <input asp-for="PageNumber" class="form-control"/> *@
            @Model.PageNumber
        </div>
        <div>
            / @Model.TotalPage
        </div>
        <div class="form-group">
            <form method="post" asp-page-handler="NextPage">
                <button type="submit" class="btn btn-primary">Next Page</button>
            </form>
        </div>
    </div>
</div>